name: payplan-workaround
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: https://github.com/quoteddev/payplan-workaround
  name: payplan-workaround
